import Phaser from "phaser";
import { EventBus } from "../EventBus";

export class PreloadScene extends Phaser.Scene {
  private assetsLoaded = false;
  private readyText?: Phaser.GameObjects.Text;
  private tapText?: Phaser.GameObjects.Text;

  constructor() {
    super("PreloadScene");
  }

  create(): void {
    const { width, height } = this.scale;

    this.readyText = this.add
      .text(width / 2, height / 2 - 20, "Loading assets...", {
        fontSize: "24px",
        color: "#00d4ff",
        fontFamily: "monospace",
      })
      .setOrigin(0.5);

    this.tapText = this.add
      .text(width / 2, height / 2 + 20, "Waiting for AI art...", {
        fontSize: "14px",
        color: "#888888",
        fontFamily: "monospace",
      })
      .setOrigin(0.5);

    this.tweens.add({
      targets: this.tapText,
      alpha: 0.3,
      duration: 800,
      yoyo: true,
      repeat: -1,
    });

    // Listen for assets from React (generated by AI pipeline)
    EventBus.on(
      "load-generated-assets",
      (assets: Record<string, string>) => {
        this.loadGeneratedAssets(assets);
      }
    );

    // Listen for game start signal from React
    EventBus.on("start-game", () => {
      this.scene.start("GameScene", { levelIndex: 0 });
    });

    // Emit scene-ready so React knows we're listening
    EventBus.emit("current-scene-ready", this);

    // Also allow manual start via tap/click (fallback if no assets arrive)
    this.input.once("pointerdown", () => {
      if (!this.assetsLoaded) {
        // Start with fallback sprites
        this.scene.start("GameScene", { levelIndex: 0 });
      }
    });

    this.input.keyboard?.once("keydown-SPACE", () => {
      if (!this.assetsLoaded) {
        this.scene.start("GameScene", { levelIndex: 0 });
      }
    });
  }

  private loadGeneratedAssets(assets: Record<string, string>): void {
    const textureKeys = Object.keys(assets);
    let loaded = 0;
    let pending = 0;

    textureKeys.forEach((key) => {
      const base64 = assets[key];
      if (base64 && typeof base64 === "string") {
        pending++;
        // addBase64 is async — listen for the file-complete event
        this.textures.addBase64(key, `data:image/png;base64,${base64}`);
      }
    });

    if (pending === 0) {
      // No valid assets, just auto-start with fallbacks
      this.autoStartGame();
      return;
    }

    // Listen for each texture to finish loading
    const onTextureAdded = () => {
      loaded++;
      if (loaded >= pending) {
        this.textures.off("onload", onTextureAdded);
        this.textures.off("onerror", onTextureError);
        this.assetsLoaded = true;
        EventBus.emit("assets-loaded", { loaded, total: textureKeys.length });
        this.autoStartGame();
      }
    };

    const onTextureError = () => {
      loaded++;
      if (loaded >= pending) {
        this.textures.off("onload", onTextureAdded);
        this.textures.off("onerror", onTextureError);
        this.assetsLoaded = true;
        this.autoStartGame();
      }
    };

    this.textures.on("onload", onTextureAdded);
    this.textures.on("onerror", onTextureError);

    // Safety timeout — don't wait forever (10 seconds)
    this.time.delayedCall(10000, () => {
      if (!this.assetsLoaded) {
        this.assetsLoaded = true;
        this.textures.off("onload", onTextureAdded);
        this.textures.off("onerror", onTextureError);
        this.autoStartGame();
      }
    });
  }

  private autoStartGame(): void {
    if (this.readyText) {
      this.readyText.setText("Ready to Play!");
    }
    if (this.tapText) {
      this.tapText.setText("Starting...");
    }

    // Brief delay so the user sees the "Ready" message
    this.time.delayedCall(500, () => {
      this.scene.start("GameScene", { levelIndex: 0 });
    });
  }

  shutdown(): void {
    // Clean up EventBus listeners when scene shuts down
    EventBus.off("load-generated-assets");
    EventBus.off("start-game");
  }
}
