import Phaser from "phaser";
import { EventBus } from "../EventBus";

export class PreloadScene extends Phaser.Scene {
  private assetsLoaded = false;
  private readyText?: Phaser.GameObjects.Text;
  private tapText?: Phaser.GameObjects.Text;

  constructor() {
    super("PreloadScene");
  }

  create(): void {
    const { width, height } = this.scale;

    this.readyText = this.add
      .text(width / 2, height / 2 - 20, "Loading assets...", {
        fontSize: "24px",
        color: "#00d4ff",
        fontFamily: "monospace",
      })
      .setOrigin(0.5);

    this.tapText = this.add
      .text(width / 2, height / 2 + 20, "Waiting for AI art...", {
        fontSize: "14px",
        color: "#888888",
        fontFamily: "monospace",
      })
      .setOrigin(0.5);

    this.tweens.add({
      targets: this.tapText,
      alpha: 0.3,
      duration: 800,
      yoyo: true,
      repeat: -1,
    });

    // Listen for assets from React (generated by AI pipeline)
    EventBus.on(
      "load-generated-assets",
      (assets: Record<string, string>) => {
        this.loadGeneratedAssets(assets);
      }
    );

    // Listen for story data from React — store in Phaser registry
    EventBus.on(
      "load-story-data",
      (story: unknown) => {
        this.registry.set("story", story);
      }
    );

    // Listen for madlibs entries — store for weapon type derivation
    EventBus.on(
      "load-entries-data",
      (entries: Record<string, string>) => {
        this.registry.set("entries", entries);
      }
    );

    // Listen for game start signal from React
    EventBus.on("start-game", () => {
      this.scene.start("GameScene", { levelIndex: 0 });
    });

    // Emit scene-ready so React knows we're listening
    EventBus.emit("current-scene-ready", this);

    // Also allow manual start via tap/click (fallback if no assets arrive)
    this.input.once("pointerdown", () => {
      if (!this.assetsLoaded) {
        this.scene.start("GameScene", { levelIndex: 0 });
      }
    });

    this.input.keyboard?.once("keydown-SPACE", () => {
      if (!this.assetsLoaded) {
        this.scene.start("GameScene", { levelIndex: 0 });
      }
    });
  }

  private loadGeneratedAssets(assets: Record<string, string>): void {
    const expectedKeys = new Set<string>();

    Object.entries(assets).forEach(([key, base64]) => {
      if (base64 && typeof base64 === "string") {
        expectedKeys.add(key);

        // Remove the placeholder texture created by BootScene so we can
        // replace it with the AI-generated version without collision
        if (this.textures.exists(key)) {
          this.textures.remove(key);
        }

        this.textures.addBase64(key, `data:image/png;base64,${base64}`);
      }
    });

    if (expectedKeys.size === 0) {
      this.autoStartGame();
      return;
    }

    let loaded = 0;
    const total = expectedKeys.size;

    // addBase64 is async — fires "addtexture" when each image finishes loading
    const onTextureAdded = (addedKey: string) => {
      if (expectedKeys.has(addedKey)) {
        loaded++;
        if (this.tapText) {
          this.tapText.setText(`Loaded ${loaded} / ${total}...`);
        }
        if (loaded >= total) {
          this.textures.off("addtexture", onTextureAdded);
          this.assetsLoaded = true;
          EventBus.emit("assets-loaded", { loaded, total });
          this.autoStartGame();
        }
      }
    };

    this.textures.on("addtexture", onTextureAdded);

    // Safety timeout — don't wait forever (15 seconds)
    this.time.delayedCall(15000, () => {
      if (!this.assetsLoaded) {
        this.assetsLoaded = true;
        this.textures.off("addtexture", onTextureAdded);
        this.autoStartGame();
      }
    });
  }

  private autoStartGame(): void {
    if (this.readyText) {
      this.readyText.setText("Ready to Play!");
    }
    if (this.tapText) {
      this.tapText.setText("Starting...");
    }

    // Brief delay so the user sees the "Ready" message
    this.time.delayedCall(500, () => {
      this.scene.start("GameScene", { levelIndex: 0 });
    });
  }

  shutdown(): void {
    EventBus.off("load-generated-assets");
    EventBus.off("load-story-data");
    EventBus.off("load-entries-data");
    EventBus.off("start-game");
  }
}
