import Phaser from "phaser";
import { EventBus } from "../EventBus";

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super("PreloadScene");
  }

  create(): void {
    const { width, height } = this.scale;

    const readyText = this.add
      .text(width / 2, height / 2, "Ready to Play!", {
        fontSize: "24px",
        color: "#00d4ff",
        fontFamily: "monospace",
      })
      .setOrigin(0.5);

    const tapText = this.add
      .text(width / 2, height / 2 + 40, "Tap or click to start", {
        fontSize: "14px",
        color: "#888888",
        fontFamily: "monospace",
      })
      .setOrigin(0.5);

    this.tweens.add({
      targets: tapText,
      alpha: 0.3,
      duration: 800,
      yoyo: true,
      repeat: -1,
    });

    // Click/tap to start immediately (uses fallback sprites)
    this.input.once("pointerdown", () => {
      this.scene.start("GameScene", { levelIndex: 0 });
    });

    this.input.keyboard?.once("keydown-SPACE", () => {
      this.scene.start("GameScene", { levelIndex: 0 });
    });

    EventBus.emit("current-scene-ready", this);

    // Listen for assets from React (generated by AI pipeline)
    EventBus.on("load-generated-assets", (assets: Record<string, string>) => {
      this.loadGeneratedAssets(assets);
    });

    // Listen for game start signal from React
    EventBus.on("start-game", () => {
      this.scene.start("GameScene", { levelIndex: 0 });
    });
  }

  private loadGeneratedAssets(assets: Record<string, string>): void {
    const textureKeys = Object.keys(assets);
    let loaded = 0;

    textureKeys.forEach((key) => {
      const base64 = assets[key];
      if (base64 && typeof base64 === "string") {
        this.textures.addBase64(key, `data:image/png;base64,${base64}`);
        loaded++;
      }
    });

    EventBus.emit("assets-loaded", { loaded, total: textureKeys.length });
  }
}
